# Review Problems

**1)    Define the following metrics and perform the following operations**

Matrix A =  [[ 3.7827  3.3454  3.2341]  , [ 2.2122  3.5678  3.9087] ,
[1.1234  2.8934,  5.9087]].

Matrix B =  [[ 3.1234  3.0987  3.1234]  , [ 2.1111  3.2222  3.3333] ,
[1.0987  1.3456,  5.1234]].

Matrix C =  [[ 3.1243  3.0989  3.1256 ]  , [ 2.6721  3.6785  3.9017] ,
[1.1254  2.8956,  5.9187]].

i)	Write a Python program using Python Lists

In [69]:
import timeit

# Define matrices using python lists
def define_matrices():
    matrix_a = [[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]]
    matrix_b = [[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]]
    matrix_c = [[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]]
    return matrix_a, matrix_b, matrix_c

# Matrix operations using python lists
def matrix_operations():
    A, B, C = define_matrices()
    
    # Matrix Addition
    result_add = [[A[i][j] + B[i][j] for j in range(len(A[0]))] for i in range(len(A))]
    
    # Matrix Subtraction
    result_sub = [[A[i][j] - C[i][j] for j in range(len(A[0]))] for i in range(len(A))]
    
    # Matrix Multiplication
    result_mul = [[A[i][j] * B[i][j] for j in range(len(A[0]))] for i in range(len(A))]
    
    # Matrix Division
    result_div = [[A[i][j] / B[i][j] for j in range(len(A[0]))] for i in range(len(A))]
    
    return result_add, result_sub, result_mul, result_div

# Measure execution time of matrix definition
def time_define_matrices():
    define_matrices()

# Measure execution time of matrix operations
def time_matrix_operations():
    matrix_operations()

# Timing the matrix definition using python lists
execution_time_define = timeit.timeit(time_define_matrices, number=10000)
print(f"Execution time for matrix definition with Python lists: {execution_time_define:.6f} seconds")

# Timing the matrix operations using python lists
execution_time_operations = timeit.timeit(time_matrix_operations, number=1000)
print(f"Execution time for matrix operations with Python lists: {execution_time_operations:.6f} seconds")

# Print matrices and results of operations
def print_matrices():
    A, B, C = define_matrices()
    print("Matrix A:")
    for row in A:
        print(row)
    print("\nMatrix B:")
    for row in B:
        print(row)
    print("\nMatrix C:")
    for row in C:
        print(row)

def print_operations():
    result_add, result_sub, result_mul, result_div = matrix_operations()
    
    print("\nMatrix Addition Result:")
    for row in result_add:
        print(row)
    
    print("\nMatrix Subtraction Result:")
    for row in result_sub:
        print(row)
    
    print("\nMatrix Multiplication Result:")
    for row in result_mul:
        print(row)
    
    print("\nMatrix Division Result:")
    for row in result_div:
        print(row)

# Execute and print results
print("Matrices:")
print_matrices()

print("\nResults of Matrix Operations:")
print_operations()


Execution time for matrix definition with Python lists: 0.011538 seconds
Execution time for matrix operations with Python lists: 0.013200 seconds
Matrices:
Matrix A:
[3.7827, 3.3454, 3.2341]
[2.2122, 3.5678, 3.9087]
[1.1234, 2.8934, 5.9087]

Matrix B:
[3.1234, 3.0987, 3.1234]
[2.1111, 3.2222, 3.3333]
[1.0987, 1.3456, 5.1234]

Matrix C:
[3.1243, 3.0989, 3.1256]
[2.6721, 3.6785, 3.9017]
[1.1254, 2.8956, 5.9187]

Results of Matrix Operations:

Matrix Addition Result:
[6.9061, 6.444100000000001, 6.3575]
[4.3233, 6.79, 7.242]
[2.2221, 4.239, 11.0321]

Matrix Subtraction Result:
[0.6584000000000003, 0.24650000000000016, 0.10850000000000026]
[-0.45989999999999975, -0.11070000000000002, 0.007000000000000117]
[-0.0020000000000000018, -0.0021999999999997577, -0.010000000000000675]

Matrix Multiplication Result:
[11.814885180000001, 10.36639098, 10.10138794]
[4.6701754200000005, 11.49616516, 13.02886971]
[1.23427958, 3.89335904, 30.27263358]

Matrix Division Result:
[1.2110840750464238, 1.0796140

ii)	Write a Python program and NumPy

In [67]:
import numpy as np
import timeit

# Define matrices using NumPy
def define_matrices_numpy():
    matrix_a = np.array([[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]])
    matrix_b = np.array([[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]])
    matrix_c = np.array([[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]])
    
    return matrix_a, matrix_b, matrix_c

# Matrix operations using NumPy
def matrix_operations_numpy():
    A, B, C = define_matrices_numpy()
    
    # Matrix Addition
    result_add = A + B
    
    # Matrix Subtraction
    result_sub = A - C
    
    # Matrix Multiplication
    result_mul = A * B
    
    # Matrix Division
    result_div = A / B
    
    return result_add, result_sub, result_mul, result_div

# Measure execution time of matrix definition
def time_define_matrices_numpy():
    define_matrices_numpy()

# Measure execution time of matrix operations
def time_matrix_operations_numpy():
    matrix_operations_numpy()

# Timing the matrix definition
execution_time_define_numpy = timeit.timeit(time_define_matrices_numpy, number=10000)
print(f"Execution time for matrix definition with NumPy: {execution_time_define_numpy:.6f} seconds")

# Timing the matrix operations
execution_time_operations_numpy = timeit.timeit(time_matrix_operations_numpy, number=1000)
print(f"Execution time for matrix operations with NumPy: {execution_time_operations_numpy:.6f} seconds")

# Print matrices and results of operations
def print_matrices_numpy():
    A, B, C = define_matrices_numpy()
    print("Matrix A:")
    print(A)
    print("\nMatrix B:")
    print(B)
    print("\nMatrix C:")
    print(C)

def print_operations_numpy():
    result_add, result_sub, result_mul, result_div = matrix_operations_numpy()
    
    print("\nMatrix Addition Result:")
    print(result_add)
    
    print("\nMatrix Subtraction Result:")
    print(result_sub)
    
    print("\nMatrix Multiplication Result:")
    print(result_mul)
    
    print("\nMatrix Division Result:")
    print(result_div)

# Execute and print results
print("Matrices:")
print_matrices_numpy()

print("\nResults of Matrix Operations:")
print_operations_numpy()


Execution time for matrix definition with NumPy: 0.229484 seconds
Execution time for matrix operations with NumPy: 0.065482 seconds
Matrices:
Matrix A:
[[3.7827 3.3454 3.2341]
 [2.2122 3.5678 3.9087]
 [1.1234 2.8934 5.9087]]

Matrix B:
[[3.1234 3.0987 3.1234]
 [2.1111 3.2222 3.3333]
 [1.0987 1.3456 5.1234]]

Matrix C:
[[3.1243 3.0989 3.1256]
 [2.6721 3.6785 3.9017]
 [1.1254 2.8956 5.9187]]

Results of Matrix Operations:

Matrix Addition Result:
[[ 6.9061  6.4441  6.3575]
 [ 4.3233  6.79    7.242 ]
 [ 2.2221  4.239  11.0321]]

Matrix Subtraction Result:
[[ 0.6584  0.2465  0.1085]
 [-0.4599 -0.1107  0.007 ]
 [-0.002  -0.0022 -0.01  ]]

Matrix Multiplication Result:
[[11.81488518 10.36639098 10.10138794]
 [ 4.67017542 11.49616516 13.02886971]
 [ 1.23427958  3.89335904 30.27263358]]

Matrix Division Result:
[[1.21108408 1.07961403 1.03544215]
 [1.04788973 1.10725591 1.17262173]
 [1.02248111 2.15026754 1.15327712]]


2)	Write a Python Program and perform the following operations ?

I.	Create a List {1225, 4986, 6789, 7890, 2345, 6783, 0987, 1234, 8765, 3456}

II.	Iterate using a for loop

III.	Iterate using for loop and range

IV.	List Comprehension

V.	Enumerate

VI.	Iter function and next function

VII.	Map function

VIII.	Using zip

IX.	Using NumPy Module


In [41]:
import numpy as np
import timeit

# Define the list
my_list = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

def double(num):
    return num * 2

# I. Create a List
def create_list():
    return [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

# II. Iterate using a for loop
def iterate_for_loop(lst):
    result = []
    for item in lst:
        result.append(double(item))
    return result

# III. Iterate using for loop and range
def iterate_for_loop_range(lst):
    result = []
    for i in range(len(lst)):
        result.append(double(lst[i]))
    return result

# IV. List Comprehension
def list_comprehension(lst):
    return [double(x) for x in lst]

# V. Enumerate
def enumerate_example(lst):
    return list(enumerate(lst))

# VI. Iter function and next function
def iter_next_example(lst):
    iterator = iter(lst)
    result = []
    while True:
        try:
            result.append(double(next(iterator)))
        except StopIteration:
            break
    return result

# VII. Map function
def map_function(lst):
    return list(map(double, lst))

# VIII. Using zip
def zip_example(lst):
    another_list = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
    return list(zip(lst, another_list))

# IX. Using NumPy Module
def numpy_example(lst):
    np_array = np.array(lst)
    return list(np_array * 2)

# Function to profile operations
def profile_operations():
    print("Profile Data:")
    
    # Timing each operation
    time_create_list = timeit.timeit(create_list, number=1)
    print(f"I. Creating a List: {time_create_list:.6f} seconds")
    
    time_for_loop = timeit.timeit(lambda: iterate_for_loop(my_list), number=10000)
    print(f"II. Iterating using a for loop: {time_for_loop:.6f} seconds")
    
    time_for_loop_range = timeit.timeit(lambda: iterate_for_loop_range(my_list), number=10000)
    print(f"III. Iterating using for loop and range: {time_for_loop_range:.6f} seconds")
    
    time_list_comprehension = timeit.timeit(lambda: list_comprehension(my_list), number=10000)
    print(f"IV. List Comprehension: {time_list_comprehension:.6f} seconds")
    
    time_enumerate = timeit.timeit(lambda: enumerate_example(my_list), number=10000)
    print(f"V. Enumerate: {time_enumerate:.6f} seconds")
    
    time_iter_next = timeit.timeit(lambda: iter_next_example(my_list), number=10000)
    print(f"VI. Iter function and next function: {time_iter_next:.6f} seconds")
    
    time_map_function = timeit.timeit(lambda: map_function(my_list), number=10000)
    print(f"VII. Map function: {time_map_function:.6f} seconds")
    
    time_zip_example = timeit.timeit(lambda: zip_example(my_list), number=10000)
    print(f"VIII. Using zip: {time_zip_example:.6f} seconds")
    
    time_numpy_example = timeit.timeit(lambda: numpy_example(my_list), number=10000)
    print(f"IX. Using NumPy Module: {time_numpy_example:.6f} seconds")

    print("\nOutput:")
    
    # Printing outputs
    print("create_list:")
    print(create_list())
    
    print("\niterate_for_loop:")
    print(iterate_for_loop(my_list))
    
    print("\niterate_for_loop_range:")
    print(iterate_for_loop_range(my_list))
    
    print("\nlist_comprehension:")
    print(list_comprehension(my_list))
    
    print("\nenumerate_example:")
    print(enumerate_example(my_list))
    
    print("\niter_next_example:")
    print(iter_next_example(my_list))
    
    print("\nmap_function:")
    print(map_function(my_list))
    
    print("\nzip_example:")
    print(zip_example(my_list))
    
    print("\nnumPy_example:")
    print(numpy_example(my_list))

if __name__ == "__main__":
    profile_operations()


Profile Data:
I. Creating a List: 0.000003 seconds
II. Iterating using a for loop: 0.015757 seconds
III. Iterating using for loop and range: 0.021012 seconds
IV. List Comprehension: 0.020164 seconds
V. Enumerate: 0.008472 seconds
VI. Iter function and next function: 0.023900 seconds
VII. Map function: 0.018924 seconds
VIII. Using zip: 0.009880 seconds
IX. Using NumPy Module: 0.085351 seconds

Output:
create_list:
[1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

iterate_for_loop:
[2450, 9972, 13578, 15780, 4690, 13566, 1974, 2468, 17530, 6912]

iterate_for_loop_range:
[2450, 9972, 13578, 15780, 4690, 13566, 1974, 2468, 17530, 6912]

list_comprehension:
[2450, 9972, 13578, 15780, 4690, 13566, 1974, 2468, 17530, 6912]

enumerate_example:
[(0, 1225), (1, 4986), (2, 6789), (3, 7890), (4, 2345), (5, 6783), (6, 987), (7, 1234), (8, 8765), (9, 3456)]

iter_next_example:
[2450, 9972, 13578, 15780, 4690, 13566, 1974, 2468, 17530, 6912]

map_function:
[2450, 9972, 13578, 15780, 4690, 

3)	For a List A, B, C, D, E write a python program to compute all the combinations and permutations 

In [49]:
import itertools
import timeit

# Define the list
elements = ['A', 'B', 'C', 'D', 'E']

def profile_combinations(elements):
    """Compute and profile all combinations of the elements."""
    print("Profiling Combinations:")
    
    total_combinations = []
    for r in range(1, len(elements) + 1):
        # Profile combination generation
        start_time = timeit.default_timer()
        combs = list(itertools.combinations(elements, r))
        elapsed = timeit.default_timer() - start_time
        
        total_combinations.extend(combs)
        
        print(f"Length {r}: {len(combs)} combinations (Time: {elapsed:.6f} seconds)")
    
    print(f"\nTotal Combinations: {len(total_combinations)}")
    # Print all combinations
    print("\nAll Combinations:")
    for comb in total_combinations:
        print(comb)

def profile_permutations(elements):
    """Compute and profile all permutations of the elements."""
    print("\nProfiling Permutations:")
    
    total_permutations = []
    for r in range(1, len(elements) + 1):
        # Profile permutation generation
        start_time = timeit.default_timer()
        perms = list(itertools.permutations(elements, r))
        elapsed = timeit.default_timer() - start_time
        
        total_permutations.extend(perms)
        
        print(f"Length {r}: {len(perms)} permutations (Time: {elapsed:.6f} seconds)")
    
    print(f"\nTotal Permutations: {len(total_permutations)}")
    # Print all permutations
    print("\nAll Permutations:")
    for perm in total_permutations:
        print(perm)

if __name__ == "__main__":
    profile_combinations(elements)
    profile_permutations(elements)


Profiling Combinations:
Length 1: 5 combinations (Time: 0.000007 seconds)
Length 2: 10 combinations (Time: 0.000003 seconds)
Length 3: 10 combinations (Time: 0.000003 seconds)
Length 4: 5 combinations (Time: 0.000003 seconds)
Length 5: 1 combinations (Time: 0.000002 seconds)

Total Combinations: 31

All Combinations:
('A',)
('B',)
('C',)
('D',)
('E',)
('A', 'B')
('A', 'C')
('A', 'D')
('A', 'E')
('B', 'C')
('B', 'D')
('B', 'E')
('C', 'D')
('C', 'E')
('D', 'E')
('A', 'B', 'C')
('A', 'B', 'D')
('A', 'B', 'E')
('A', 'C', 'D')
('A', 'C', 'E')
('A', 'D', 'E')
('B', 'C', 'D')
('B', 'C', 'E')
('B', 'D', 'E')
('C', 'D', 'E')
('A', 'B', 'C', 'D')
('A', 'B', 'C', 'E')
('A', 'B', 'D', 'E')
('A', 'C', 'D', 'E')
('B', 'C', 'D', 'E')
('A', 'B', 'C', 'D', 'E')

Profiling Permutations:
Length 1: 5 permutations (Time: 0.000004 seconds)
Length 2: 20 permutations (Time: 0.000003 seconds)
Length 3: 60 permutations (Time: 0.000020 seconds)
Length 4: 120 permutations (Time: 0.000448 seconds)
Length 5: 120 pe

4)	Using the same list use itertools compute permutations and combinations 

In [51]:
import itertools
import math
import timeit

# Define the list
elements = ['A', 'B', 'C', 'D', 'E']

def compute_and_list_permutations():
    all_permutations = []
    for r in range(1, len(elements) + 1):
        perms = list(itertools.permutations(elements, r))
        all_permutations.extend(perms)
    return all_permutations

def compute_and_list_combinations():
    all_combinations = []
    for r in range(1, len(elements) + 1):
        combs = list(itertools.combinations(elements, r))
        all_combinations.extend(combs)
    return all_combinations

def profile_permutations_combinations():
    # Timing permutations computation and listing
    start_time = timeit.default_timer()
    permutations_list = compute_and_list_permutations()
    end_time = timeit.default_timer()
    elapsed_time_permutations = end_time - start_time

    # Timing combinations computation and listing
    start_time = timeit.default_timer()
    combinations_list = compute_and_list_combinations()
    end_time = timeit.default_timer()
    elapsed_time_combinations = end_time - start_time

    # Printing results
    print("Permutations:")
    for perm in permutations_list:
        print(perm)
    print(f"Total number of permutations: {len(permutations_list)}")
    print(f"Time for computing permutations: {elapsed_time_permutations:.6f} seconds")
    
    print("\nCombinations:")
    for comb in combinations_list:
        print(comb)
    print(f"Total number of combinations: {len(combinations_list)}")
    print(f"Time for computing combinations: {elapsed_time_combinations:.6f} seconds")

if __name__ == "__main__":
    profile_permutations_combinations()


Permutations:
('A',)
('B',)
('C',)
('D',)
('E',)
('A', 'B')
('A', 'C')
('A', 'D')
('A', 'E')
('B', 'A')
('B', 'C')
('B', 'D')
('B', 'E')
('C', 'A')
('C', 'B')
('C', 'D')
('C', 'E')
('D', 'A')
('D', 'B')
('D', 'C')
('D', 'E')
('E', 'A')
('E', 'B')
('E', 'C')
('E', 'D')
('A', 'B', 'C')
('A', 'B', 'D')
('A', 'B', 'E')
('A', 'C', 'B')
('A', 'C', 'D')
('A', 'C', 'E')
('A', 'D', 'B')
('A', 'D', 'C')
('A', 'D', 'E')
('A', 'E', 'B')
('A', 'E', 'C')
('A', 'E', 'D')
('B', 'A', 'C')
('B', 'A', 'D')
('B', 'A', 'E')
('B', 'C', 'A')
('B', 'C', 'D')
('B', 'C', 'E')
('B', 'D', 'A')
('B', 'D', 'C')
('B', 'D', 'E')
('B', 'E', 'A')
('B', 'E', 'C')
('B', 'E', 'D')
('C', 'A', 'B')
('C', 'A', 'D')
('C', 'A', 'E')
('C', 'B', 'A')
('C', 'B', 'D')
('C', 'B', 'E')
('C', 'D', 'A')
('C', 'D', 'B')
('C', 'D', 'E')
('C', 'E', 'A')
('C', 'E', 'B')
('C', 'E', 'D')
('D', 'A', 'B')
('D', 'A', 'C')
('D', 'A', 'E')
('D', 'B', 'A')
('D', 'B', 'C')
('D', 'B', 'E')
('D', 'C', 'A')
('D', 'C', 'B')
('D', 'C', 'E')
('D', 'E', 